server:
  port: 5015



spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://39.96.179.255:3306/lottery?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml